name: Gym Availability Checker

on:
  schedule: # (skip JST 01:00-05:59) other every 40 min
    - cron: "*/40 21-23 * * *" # 21:00-23:59 UTC (06:00-08:59 JST)
    - cron: "*/40 0-15 * * *" # 0:00-15:59 UTC (09:00-00:59 JST)
  workflow_dispatch: # Allow manual triggering

jobs:
  check-availability:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Create .env file
        run: |
          echo "LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" > .env
          echo "LINE_USER_ID=${{ secrets.LINE_USER_ID }}" >> .env
          echo "LINE_GROUP_ID=${{ secrets.LINE_GROUP_ID }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "USER_ID=${{ secrets.USER_ID }}" >> .env
          echo "TAI_PASSWORD=${{ secrets.TAI_PASSWORD }}" >> .env
          echo "TAI_USER_ID=${{ secrets.TAI_USER_ID }}" >> .env
          echo "RANGE_MINUTES=${{ secrets.RANGE_MINUTES || '15' }}" >> .env

      - name: Run availability check
        run: pnpm test

      - name: Upload test results
        if: always() # Always run this step, even if the test fails
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            e2e-result/
            playwright-report/
          retention-days: 7
